# Generated by Django 3.0.8 on 2020-09-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
