# Generated by Django 3.0.8 on 2020-09-12 14:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0002_user_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='last_check_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 12, 14, 55, 17, 924020, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
