# Generated by Django 3.0.8 on 2023-03-19 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0004_track_artwork_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='access_users',
        ),
        migrations.AddField(
            model_name='user',
            name='requested_room',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='join_requests', to='musicroom.Room'),
        ),
        migrations.AddField(
            model_name='user',
            name='room_visible_to_friends',
            field=models.BooleanField(default=True),
        ),
    ]
