# Generated by Django 3.0.8 on 2023-03-27 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0005_auto_20230319_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artist',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='id',
        ),
        migrations.AddField(
            model_name='artist',
            name='image_path',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='ref_id',
            field=models.CharField(default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='slug',
            field=models.CharField(default='0', max_length=255, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='track',
            name='language',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='roomtrack',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='roomtracks', to='musicroom.Track'),
        ),
        migrations.CreateModel(
            name='TrackArtist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicroom.Artist')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicroom.Track')),
            ],
            options={
                'unique_together': {('track', 'artist'), ('track', 'index')},
            },
        ),
        migrations.AddField(
            model_name='track',
            name='artists_link',
            field=models.ManyToManyField(related_name='tracks', through='musicroom.TrackArtist', to='musicroom.Artist'),
        ),
    ]
