# Generated by Django 3.0.8 on 2023-03-28 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0008_auto_20230327_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_play_duration_secs',
            field=models.IntegerField(default=0),
        ),
    ]
