# Generated by Django 3.0.8 on 2023-03-28 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0010_playbackhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='current_play_duration_secs',
            new_name='play_count',
        ),
        migrations.AddField(
            model_name='playbackhistory',
            name='play_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='playbackhistory',
            unique_together={('user', 'play_id')},
        ),
    ]
