# Generated by Django 3.0.8 on 2023-03-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0011_auto_20230328_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='spotify_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
