# Generated by Django 3.0.8 on 2023-04-01 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('musicroom', '0012_track_spotify_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTrackRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musicroom.Track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_track_recommendation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'track')},
            },
        ),
        migrations.CreateModel(
            name='TrackTrackRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recommended_track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='musicroom.Track')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_track_recommendation', to='musicroom.Track')),
            ],
            options={
                'unique_together': {('track', 'recommended_track')},
            },
        ),
    ]
